### PR TITLE
[DOCS] Adapt README file

### PR DESCRIPTION
**Pull request by alexander-nitsche**
- use reST everywhere, skip markdown (GitHub also understands it)
- use template of similar extensions like EXT:extension_builder and EXT:news
- fine-tune translation with deepl.com
- add the link to the TER page of the extension to lead the user directly to the installation

### CODE REVIEW

**Comment by alexander-nitsche** [comment]
Hi Armin, just became aware of your documentation rendering request today and looked by. I recommend some changes to the README file. Besides that, you might want to adapt the link in your [TER page](https://extensions.typo3.org/extension/min) where the button "Extension Manual" links to the old documentation at https://docs.typo3.org/typo3cms/extensions/min/.

**Comment by a-r-m-i-n** [comment]
Oh... I just double checked it, now the link in TER works.

**Comment by a-r-m-i-n** [comment]
I'm going to close this pull request, because I've applied your content suggestions, in a separate commit.

**Comment by alexander-nitsche** [comment]
Ok, sure. I would remove the "Documentation" section in your current README.md as it seems to be a duplicate of the "Links" section.

**Comment by a-r-m-i-n** [comment]
Documentation worth to be mentioned twice! ;-)

**Comment by alexander-nitsche** [comment]
Aye, no further remarks then :)

**Pull request closed without merging**
